# Generated by Django 6.0.1 on 2026-08-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgame',
            name='plaintext',
            field=models.TextField(blank=True, default=''),
        ),
    ]
