# Generated by Django 6.0.1 on 2026-08-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_alter_savedgame_plaintext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedgame',
            name='solution_hash',
        ),
    ]
