# Generated by Django 6.0.1 on 2026-08-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solverecord',
            name='character_type',
            field=models.CharField(choices=[('alphabetic', 'Alphabetic'), ('numeric', 'Numeric')], max_length=10),
        ),
        migrations.AlterField(
            model_name='solverecord',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
    ]
