# Generated by Django 6.0.1 on 2026-08-22 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_quote',
        ),
    ]
